version: '3'

services:

  db1:
    image: 'mysql:5'
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    container_name: 'db1'
    ports:
      - '3307:3306'
    volumes:
      - './config/db1/mysql:/etc/mysql'

  db2:
    image: 'mysql:5'
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    container_name: 'db2'
    ports:
      - '3308:3306'
    volumes:
      - './config/db2/mysql:/etc/mysql'
